In [1]:
a = 10
b = 3

f'{a/b:.2f}'

'3.33'

In [2]:
import random

random.randint(0, 3)

1

In [3]:
import torch
import numpy as np

x = np.zeros((20,30))
x[1,1] = 1
x[5,5] = 2

print(x[0].shape)

(30,)


In [4]:
final = torch.tensor(x).unsqueeze(0).unsqueeze(0)
print(final.shape)

torch.Size([1, 1, 20, 30])


In [5]:
import random

sampledir = []
for i in range(2):
    sampledir.append(np.random.rand(2,2))

random.sample(sampledir, 2)


[array([[0.6592034 , 0.08761486],
        [0.50709312, 0.2108339 ]]),
 array([[4.51328462e-01, 9.80980194e-01],
        [1.73013855e-04, 9.64508001e-01]])]

In [6]:
cool = bool(random.randint(0,1))
print(cool)
for i in range(len((cool, ))):
    print(i)

True
0


In [7]:
import numpy as np
import torch
ran = np.arange(4)
print(ran)
ran_tensor = torch.tensor(ran, dtype=torch.float)
ran_tensor_usq = torch.tensor(ran, dtype=torch.float).unsqueeze(0)
print(f"unsqueezed max: {torch.max(ran_tensor_usq)} and normal max: {torch.max(ran_tensor)}")

[0 1 2 3]
unsqueezed max: 3.0 and normal max: 3.0


In [8]:
random.random()

0.745783584090714

In [10]:
state = np.zeros(11) # 11 features for DQN input
state

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
tt = (0, -1)
new_tt = (0, -1)
old_x, old_y = tt
new_x, new_y = new_tt
print(f"Old: {old_x}, {old_y} | New: {new_x}, {new_y}")
if (new_x, new_y) != (-old_x, -old_y):
    print("Not a 180-degree turn, update direction")
else:
    print("180-degree turn, ignore")

Old: 0, -1 | New: 0, -1
Not a 180-degree turn, update direction
